[Fri Jun 16 17:00:27.555459 2017] [:error] [pid 1168] [client 127.0.0.1:36390] PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/var/www/html/test_sf/sf/var/cache/prod/annotations" is not writable. in /var/www/html/test_sf/sf/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FilesystemCache.php(37): Doctrine\\Common\\Cache\\FileCache->__construct('/var/www/html/t...', '.doctrinecache....', 2)\n#1 /var/www/html/test_sf/sf/var/cache/prod/appProdProjectContainer.php(302): Doctrine\\Common\\Cache\\FilesystemCache->__construct('/var/www/html/t...')\n#2 /var/www/html/test_sf/sf/var/bootstrap.php.cache(2118): appProdProjectContainer->getAnnotationReaderService()\n#3 /var/www/html/test_sf/sf/var/cache/prod/appProdProjectContainer.php(3579): Symfony\\Component\\DependencyInjection\\Container->get('annotation_read...')\n#4 /var/www/html/test_sf/sf/var/bootstrap.php.cache(2118): appProdProjectContainer->getFosRest_Request_ParamFetcher_ReaderService()\n#5 /var/www/html/test_sf/sf/var/cache/prod/appProdProject in /var/www/html/test_sf/sf/vendor/jms/metadata/src/Metadata/Cache/FileCache.php on line 17
[Fri Jun 16 17:02:25.199872 2017] [:error] [pid 17524] [client 127.0.0.1:36404] PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/var/www/html/test_sf/sf/var/cache/prod/annotations" is not writable. in /var/www/html/test_sf/sf/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FilesystemCache.php(37): Doctrine\\Common\\Cache\\FileCache->__construct('/var/www/html/t...', '.doctrinecache....', 2)\n#1 /var/www/html/test_sf/sf/var/cache/prod/appProdProjectContainer.php(302): Doctrine\\Common\\Cache\\FilesystemCache->__construct('/var/www/html/t...')\n#2 /var/www/html/test_sf/sf/var/bootstrap.php.cache(2118): appProdProjectContainer->getAnnotationReaderService()\n#3 /var/www/html/test_sf/sf/var/cache/prod/appProdProjectContainer.php(3579): Symfony\\Component\\DependencyInjection\\Container->get('annotation_read...')\n#4 /var/www/html/test_sf/sf/var/bootstrap.php.cache(2118): appProdProjectContainer->getFosRest_Request_ParamFetcher_ReaderService()\n#5 /var/www/html/test_sf/sf/var/cache/prod/appProdProject in /var/www/html/test_sf/sf/vendor/jms/metadata/src/Metadata/Cache/FileCache.php on line 17
[Fri Jun 16 17:02:38.810027 2017] [:error] [pid 10024] [client 127.0.0.1:36420] PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/var/www/html/test_sf/sf/var/cache/prod/annotations" is not writable. in /var/www/html/test_sf/sf/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FilesystemCache.php(37): Doctrine\\Common\\Cache\\FileCache->__construct('/var/www/html/t...', '.doctrinecache....', 2)\n#1 /var/www/html/test_sf/sf/var/cache/prod/appProdProjectContainer.php(302): Doctrine\\Common\\Cache\\FilesystemCache->__construct('/var/www/html/t...')\n#2 /var/www/html/test_sf/sf/var/bootstrap.php.cache(2118): appProdProjectContainer->getAnnotationReaderService()\n#3 /var/www/html/test_sf/sf/var/cache/prod/appProdProjectContainer.php(3579): Symfony\\Component\\DependencyInjection\\Container->get('annotation_read...')\n#4 /var/www/html/test_sf/sf/var/bootstrap.php.cache(2118): appProdProjectContainer->getFosRest_Request_ParamFetcher_ReaderService()\n#5 /var/www/html/test_sf/sf/var/cache/prod/appProdProject in /var/www/html/test_sf/sf/vendor/jms/metadata/src/Metadata/Cache/FileCache.php on line 17
[Fri Jun 16 21:53:12.629040 2017] [:error] [pid 5454] [client 127.0.0.1:58364] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/test_sf/sf/var/logs/prod.log" could not be opened: failed to open stream: Permission denied in /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(122): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#3 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Logger.php(644): Monolog\\Logger->addRecord(500, 'Uncaught PHP Ex...', Array)\n#4 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(89): Monolog\\Logger->critical('Uncaught PHP Ex...', Ar in /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Fri Jun 16 21:55:54.569339 2017] [:error] [pid 5456] [client 127.0.0.1:58434] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/test_sf/sf/var/logs/prod.log" could not be opened: failed to open stream: Permission denied in /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(122): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\FingersCrossedHandler->handle(Array)\n#3 /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Logger.php(644): Monolog\\Logger->addRecord(500, 'Uncaught PHP Ex...', Array)\n#4 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(89): Monolog\\Logger->critical('Uncaught PHP Ex...', Ar in /var/www/html/test_sf/sf/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Fri Jun 16 22:20:55.155729 2017] [:error] [pid 5457] [client 127.0.0.1:59826] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'root', '13', Array)\n#1 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=loca...', 'root', 13, Array)\n#2 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 'root', 13, Array)\n#3 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\\DBAL\\Connection->connect()\n#4 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#5 /var/www/html/test_sf/sf/vendor in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
[Fri Jun 16 22:21:23.891648 2017] [:error] [pid 5458] [client 127.0.0.1:59828] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'root', '13', Array)\n#1 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=loca...', 'root', 13, Array)\n#2 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 'root', 13, Array)\n#3 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\\DBAL\\Connection->connect()\n#4 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#5 /var/www/html/test_sf/sf/vendor in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
[Sat Jun 17 15:57:06.560060 2017] [:error] [pid 1141] [client 127.0.0.1:49164] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'root', '13', Array)\n#1 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=loca...', 'root', 13, Array)\n#2 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 'root', 13, Array)\n#3 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\\DBAL\\Connection->connect()\n#4 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#5 /var/www/html/test_sf/sf/vendor in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
[Sat Jun 17 16:11:25.532494 2017] [:error] [pid 1140] [client 127.0.0.1:52550] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'root', '13', Array)\n#1 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=loca...', 'root', 13, Array)\n#2 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 'root', 13, Array)\n#3 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\\DBAL\\Connection->connect()\n#4 /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#5 /var/www/html/test_sf/sf/vendor in /var/www/html/test_sf/sf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
[Sat Jun 17 20:09:15.509049 2017] [:error] [pid 1140] [client 127.0.0.1:56254] PHP Fatal error:  Uncaught RuntimeException: Unable to write in the logs directory (/var/www/html/test_sf/sf/var/logs)\n in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:563\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(476): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/html/test_sf/sf/web/app.php(18): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 563
[Sat Jun 17 20:09:23.622200 2017] [:error] [pid 3797] [client 127.0.0.1:56256] PHP Fatal error:  Uncaught RuntimeException: Unable to write in the logs directory (/var/www/html/test_sf/sf/var/logs)\n in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:563\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(476): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/html/test_sf/sf/web/app.php(18): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 563
[Sat Jun 17 20:11:02.190068 2017] [:error] [pid 1138] [client 127.0.0.1:56278] PHP Fatal error:  Uncaught RuntimeException: Unable to write in the logs directory (/var/www/html/test_sf/sf/var/logs)\n in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:563\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(476): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/html/test_sf/sf/web/app.php(18): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 563
[Sat Jun 17 20:11:05.314348 2017] [:error] [pid 1142] [client 127.0.0.1:56286] PHP Fatal error:  Uncaught RuntimeException: Unable to write in the logs directory (/var/www/html/test_sf/sf/var/logs)\n in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:563\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(476): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/html/test_sf/sf/web/app.php(18): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 563
[Sat Jun 17 20:11:48.701373 2017] [:error] [pid 1139] [client 127.0.0.1:56302] PHP Fatal error:  Uncaught RuntimeException: Unable to write in the logs directory (/var/www/html/test_sf/sf/var/logs)\n in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:563\nStack trace:\n#0 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(476): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/html/test_sf/sf/web/app.php(18): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 563
[Sat Jun 17 22:29:53.526593 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP Notice:  Undefined property: Doctrine\\ORM\\Query\\QueryException::$*Exception*trace in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 70
[Sat Jun 17 22:29:53.526730 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP Stack trace:
[Sat Jun 17 22:29:53.526755 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   1. {main}() /var/www/html/test_sf/sf/web/app.php:0
[Sat Jun 17 22:29:53.526780 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle($request = *uninitialized*, $type = *uninitialized*, $catch = *uninitialized*) /var/www/html/test_sf/sf/web/app.php:18
[Sat Jun 17 22:29:53.526800 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle($request = *uninitialized*, $type = *uninitialized*, $catch = *uninitialized*) /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169
[Sat Jun 17 22:29:54.962370 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP Notice:  Undefined property: Doctrine\\ORM\\Query\\QueryException::$*Exception*trace in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 70
[Sat Jun 17 22:29:54.962439 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP Stack trace:
[Sat Jun 17 22:29:54.962480 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   1. {main}() /var/www/html/test_sf/sf/web/app.php:0
[Sat Jun 17 22:29:54.962506 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle($request = *uninitialized*, $type = *uninitialized*, $catch = *uninitialized*) /var/www/html/test_sf/sf/web/app.php:18
[Sat Jun 17 22:29:54.962528 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle($request = *uninitialized*, $type = *uninitialized*, $catch = *uninitialized*) /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169
[Sat Jun 17 22:29:56.376163 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP Notice:  Undefined property: Doctrine\\ORM\\Query\\QueryException::$*Exception*trace in /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 70
[Sat Jun 17 22:29:56.376218 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP Stack trace:
[Sat Jun 17 22:29:56.376236 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   1. {main}() /var/www/html/test_sf/sf/web/app.php:0
[Sat Jun 17 22:29:56.376255 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle($request = *uninitialized*, $type = *uninitialized*, $catch = *uninitialized*) /var/www/html/test_sf/sf/web/app.php:18
[Sat Jun 17 22:29:56.376274 2017] [:error] [pid 2320] [client 127.0.0.1:58990] PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle($request = *uninitialized*, $type = *uninitialized*, $catch = *uninitialized*) /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169
[Sun Jun 18 20:25:00.272711 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP Notice:  Undefined variable: query in /var/www/html/test_sf/sf/src/AppBundle/Repository/VisitRepository.php on line 36
[Sun Jun 18 20:25:00.273095 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP Stack trace:
[Sun Jun 18 20:25:00.273125 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP   1. {main}() /var/www/html/test_sf/sf/web/app.php:0
[Sun Jun 18 20:25:00.273142 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle() /var/www/html/test_sf/sf/web/app.php:18
[Sun Jun 18 20:25:00.273163 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169
[Sun Jun 18 20:25:00.273176 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
[Sun Jun 18 20:25:00.273182 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP   5. call_user_func_array:{/var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153}() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153
[Sun Jun 18 20:25:00.273187 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP   6. AppBundle\\Controller\\VisitController->getAction() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153
[Sun Jun 18 20:25:00.273192 2017] [:error] [pid 1150] [client 127.0.0.1:35748] PHP   7. AppBundle\\Repository\\VisitRepository->getDau() /var/www/html/test_sf/sf/src/AppBundle/Controller/VisitController.php:42
[Sun Jun 18 20:25:16.635098 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP Notice:  Undefined variable: query in /var/www/html/test_sf/sf/src/AppBundle/Repository/VisitRepository.php on line 36
[Sun Jun 18 20:25:16.635123 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP Stack trace:
[Sun Jun 18 20:25:16.635133 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP   1. {main}() /var/www/html/test_sf/sf/web/app.php:0
[Sun Jun 18 20:25:16.635140 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle() /var/www/html/test_sf/sf/web/app.php:18
[Sun Jun 18 20:25:16.635145 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169
[Sun Jun 18 20:25:16.635151 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
[Sun Jun 18 20:25:16.635157 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP   5. call_user_func_array:{/var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153}() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153
[Sun Jun 18 20:25:16.635162 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP   6. AppBundle\\Controller\\VisitController->getAction() /var/www/html/test_sf/sf/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153
[Sun Jun 18 20:25:16.635167 2017] [:error] [pid 9580] [client 127.0.0.1:35766] PHP   7. AppBundle\\Repository\\VisitRepository->getDau() /var/www/html/test_sf/sf/src/AppBundle/Controller/VisitController.php:42
